language: python

python:
  - "3.7"  # 3.7 development branch

# command to install dependencies
install:
  - pip install poetry
  - poetry install

# command to run tests
script:
  - pytest --verbose tests/